Replace `go-kit/kit/log` & `go-kit/log` & `webpa-common/logger` with uber `zap`
xmidt-org/tr1d1um pull request #324
Opened 2022-10-25 19:07 UTC by denopink

What's included:
- #322
- #323

closes #322
closes #323

2022-10-26 16:36 UTC, johnabass requested changes

2022-10-26 16:36 UTC, johnabass commented on basculeLogging.go
> +func getLogger(ctx context.Context) *zap.Logger {
This functionality should come from `sallust`

2022-10-26 16:36 UTC, johnabass commented on routes.go
> +		getLogger = func(_ context.Context) *zap.Logger {
This functionality should come from `sallust`

2022-10-26 16:36 UTC, johnabass commented on routes.go
> +				logger = sallust.Default()
Application-layer code shouldn't have logic that determines default services, like logging.  The problem is that every application will do this differently, e.g. what `tr1d1um` does for default logging might not match what `scytale` does.

Application code should just panic if not supplied a logger (or any service).  It's up to the application programmer to supply things like `sallust.Default()`.

2022-11-03 15:17 UTC, renaz6 approved these changes

2022-11-07 19:12 UTC, johnabass approved these changes

2023-01-10 17:10 UTC, merged