Renaz6/update candlelight
xmidt-org/tr1d1um pull request #346
Opened 2022-11-30 17:05 UTC by renaz6

2022-12-06 18:03 UTC, denopink requested changes
looks good but checks are failing due to go.sum/candelight issues

2022-12-07 00:56 UTC, schmidtw approved these changes

2022-12-07 18:54 UTC, johnabass approved these changes

2023-01-09 19:47 UTC, denopink requested changes
remove local go mod replace

2023-01-10 17:33 UTC, denopink approved these changes
merged main. lgtm
Cheers! 🍻

2023-01-10 17:33 UTC, merged